name: modelapp
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.15.0
  - cudatoolkit=12.1
  - numpy=1.25
  - pandas=2.2
  - jupyterlab=4.1
  - pip
  - pip:
    - tqdm==4.66.1
    - opencv-python==4.9.0.66
